version: "2"

services:
  schedule:
    container_name: schedule
    hostname: schedule
    image: ghcr.io/schedule-team/server:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env