# Generated by Django 4.2.9 on 2024-01-23 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jw_id', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('period', models.IntegerField()),
                ('credits', models.FloatField()),
                ('type_base', models.CharField(max_length=20)),
                ('type_teaching_method', models.CharField(max_length=20)),
                ('type_join_type', models.CharField(max_length=20)),
                ('type_level', models.CharField(max_length=20)),
                ('open_department', models.CharField(max_length=20)),
                ('exam_type', models.CharField(max_length=20)),
                ('grading_type', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('info', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jw_id', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jw_id', models.CharField(max_length=20, unique=True)),
                ('campus', models.CharField(max_length=20)),
                ('building', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jw_id', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jw_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('office_location', models.CharField(blank=True, max_length=100, null=True)),
                ('homepage_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jw_id', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=20)),
                ('campus', models.CharField(max_length=20)),
                ('start_week', models.IntegerField(blank=True, null=True)),
                ('end_week', models.IntegerField(blank=True, null=True)),
                ('schedule_text', models.CharField(blank=True, max_length=100, null=True)),
                ('homepage_url', models.CharField(blank=True, max_length=100, null=True)),
                ('notice_md_text', models.CharField(blank=True, max_length=10000, null=True)),
                ('homework_md_text', models.CharField(blank=True, max_length=10000, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('exams', models.ManyToManyField(blank=True, to='course.exam')),
                ('lectures', models.ManyToManyField(blank=True, to='course.lecture')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.semester')),
                ('teachers', models.ManyToManyField(blank=True, to='course.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='lesson_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.location'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='course.teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='lesson_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
        migrations.AddField(
            model_name='exam',
            name='locations',
            field=models.ManyToManyField(blank=True, to='course.location'),
        ),
    ]
