# Generated by Django 4.2.9 on 2024-01-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='homepage_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='office_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
