# Generated by Django 4.2.9 on 2024-01-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('course', '0003_alter_course_description_alter_course_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='homepage_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework_md_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='notice_md_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='schedule_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
