# Generated by Django 4.2.9 on 2024-02-01 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_code_alter_course_exam_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditableTextModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.TextField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework_md_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='course.editabletextmodel'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='notice_md_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice', to='course.editabletextmodel'),
        ),
    ]
