# Generated by Django 4.2.9 on 2024-02-23 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_editabletextmodel_alter_lesson_homework_md_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='lesson_info',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='lesson_info',
            new_name='lesson',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='exams',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='homework_md_text',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lectures',
        ),
        migrations.AddField(
            model_name='course',
            name='semesters',
            field=models.ManyToManyField(blank=True, to='course.semester'),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
    ]
