# Generated by Django 4.2.9 on 2024-02-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_rename_lesson_info_exam_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='exam_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='grading_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='open_department',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='type_base',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='type_join_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='type_level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='type_teaching_method',
            field=models.TextField(blank=True, null=True),
        ),
    ]
