# Generated by Django 4.2.9 on 2024-02-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_historicallecture_historicalhomework_historicalexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semesters',
            field=models.ManyToManyField(blank=True, related_name='semester_courses', to='course.semester'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_exams', to='course.lesson'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_homeworks', to='course.lesson'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_lectures', to='course.lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lessons', to='course.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_lessons', to='course.semester'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teacher_lessons', to='course.teacher'),
        ),
    ]
