name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE: "ghcr.io/schedule-team/server:latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build Docker image
        run: |
          docker pull "$IMAGE" || true
          docker build -t "$IMAGE" --cache-from "$IMAGE" .
      - name: Push Docker image
        run: |
          docker login ghcr.io -u ${{ github.actor }} --password-stdin <<< "${{ secrets.GITHUB_TOKEN }}"
          docker push "$IMAGE"